version: '3.4'

services:
  inflowsystem.bootstrapper:
    image: ${DOCKER_REGISTRY-}inflowsystembootstrapper
    build:
      context: .
      dockerfile: Bootstrapper/InflowSystem.Bootstrapper/Dockerfile
